### ISSUE TITLE
Create Microsoft Azure accounts for apt3k

### ISSUE THREAD

**Issue by dioscarr** [Apt3kStudio/Phone#13]
Dioscar suggested to look into DevOps (a clipped compound of "development" and "operations") is a software development methodology that combines software development (Dev) with information technology operations (Ops)

**Comment by dioscarr** [comment]
Jonathan we should create the account. Since we have a private account we DevOps for free.

**Comment by jagomez16** [comment]
We dont a have a private account with github yet. I'm planning to create an acct with Azura today

**Comment by dioscarr** [comment]
Ok, Well we can also do it with a free account as well.
