### ISSUE TITLE
Install Wear app in android phone

### ISSUE THREAD

**Issue by dioscarr** [Apt3kStudio/Phone#21]
[android-wear-part-3-set-up-wear-emulator ](http://www.technotalkative.com/android-wear-part-3-set-up-wear-emulator/)

*

**Comment by dioscarr** [comment]
[WearCheck](https://wearos.google.com/wearcheck/)

**Comment by dioscarr** [comment]
https://www.youtube.com/watch?v=InLaDVsYbmw

**Comment by dioscarr** [comment]
https://www.youtube.com/watch?v=eJ_5pTu2FHE

**Comment by dioscarr** [comment]
[Install Wear app](https://stackoverflow.com/questions/25205888/pairing-android-and-wear-emulators)

**Comment by dioscarr** [comment]
![image](https://user-images.githubusercontent.com/6876354/48872365-c03f3a00-edb6-11e8-802e-eb39c928f4aa.png)

**Comment by dioscarr** [comment]
[AndroidCommandLine](http://www.vogella.com/tutorials/AndroidCommandLine/article.html)

**Comment by dioscarr** [comment]
[command-line from android studdio](https://developer.android.com/studio/command-line/adb#move)

**Comment by dioscarr** [comment]
![image](https://user-images.githubusercontent.com/6876354/48872808-bc141c00-edb8-11e8-9628-6ebba14f8c2d.png)

**Comment by dioscarr** [comment]
![image](https://user-images.githubusercontent.com/6876354/48873505-35613e00-edbc-11e8-8e05-fda48a4af9c8.png)

**Comment by dioscarr** [comment]
![image](https://user-images.githubusercontent.com/6876354/48873513-401bd300-edbc-11e8-92b9-eb0169062ad4.png)

**Comment by dioscarr** [comment]
![image](https://user-images.githubusercontent.com/6876354/48873520-4f9b1c00-edbc-11e8-9baa-3de331d34166.png)

**Comment by dioscarr** [comment]
Android Console: Authentication required
Android Console: type 'auth <auth_token>' to authenticate
Android Console: you can find your <auth_token> in
'C:\Users\Diosc\.emulator_console_auth_token'
OK

KO: unknown command, try 'help'
aeut
KO: unknown command, try 'help'
auth C:\Users\Diosc\.emulator_console_auth_token
KO: authentication token does not match ~/.emulator_console_auth_token
auth 
KO: unknown command, try 'help'
auth
KO: unknown command, try 'help'
ko
KO: unknown command, try 'help'
auth BrM01u+kU7rE6MPK
Android Console: type 'help' for a list of commands
OK
redir add tcp:5601:5601
KO: unknown command, try 'help'

KO: unknown command, try 'help'
help
Android console commands:
    help|h|?
    help-verbose
    ping
    automation
    event
    geo
    gsm
    cdma
    crash
    crash-on-exit
    kill
    restart
    network
    power
    quit|exit
    redir
    sms
    avd
    qemu
    sensor
    physics
    finger
    debug
    rotate
    screenrecord

Try 'help-verbose' for more description
Try 'help <command>' for command-specific help
OK
help-verbose
KO: unknown command, try 'help'
help-
KO: unknown command, try 'help'
redir add tcp:5601:5601
KO: unknown command, try 'help'
redir list
no active redirections
OK
redir add tcp:5601:5601
OK
redir list
KO: unknown command, try 'help'
redir list
KO: unknown command, try 'help'
help
Android console commands:
    help|h|?
    help-verbose
    ping
    automation
    event
    geo
    gsm
    cdma
    crash
    crash-on-exit
    kill
    restart
    network
    power
    quit|exit
    redir
    sms
    avd
    qemu
    sensor
    physics
    finger
    debug
    rotate
    screenrecord

Try 'help-verbose' for more description
Try 'help <command>' for command-specific help
OK
redir
allows you to add, list and remove UDP and/or PORT redirection from the host to the device
as an example, 'redir  tcp:5000:6000' will route any packet sent to the host's TCP port 5000
to TCP port 6000 of the emulated device

available sub-commands:
    list             list current redirections
    add              add new redirection
    del              remove existing redirection

KO: missing sub-command
redir list
tcp:5601  => 5601
OK
auth BrM01u+kU7rE6MPK

**Comment by dioscarr** [comment]
![image](https://user-images.githubusercontent.com/6876354/48874664-5af14600-edc2-11e8-8fcd-cfb929d11a8e.png)

**Comment by nvasquedr** [comment]
Complete
