### ISSUE TITLE
Vibrate Event

### ISSUE THREAD

**Issue by dioscarr** [Apt3kStudio/Phone#46]
[Vibrate Event.pdf ](https://github.com/Apt3kStudio/Phone/files/2712693/Vibrate.Event.pdf)

Please implementat Phase 1.2

**Comment by dioscarr** [comment]
![image](https://user-images.githubusercontent.com/6876354/50484554-0c395c00-09bf-11e9-84d5-a48e425665d2.png)

**Comment by dioscarr** [comment]
New comment

**Comment by nvasquedr** [comment]
Issue Completed: Added vibration functionality to the phone based on an event from watch. This can be accomplished via Bluetooth and HTTP through the web portal.
