### ISSUE TITLE
Add custom icons for features

### ISSUE THREAD

**Issue by nvasquedr** [Apt3kStudio/Phone#63]
# Custom icons

Add icon for each functionality on the phone. Make sure the icons are appropriately sized to fit the buttons they will be added to. The icons can be found in the teams email/whats app chat.

## Requirement 
- [x] Vibrate icon
- [x] Sound icon
- [x] Flash icon

**Comment by Apt3k** [comment]
Link to google drive folder https://drive.google.com/drive/u/2/folders/1Rd37vqORTWiRPxsUPYFSoh-nyOAQTH9r
