### ISSUE TITLE
Create Button Icons

### ISSUE THREAD

**Issue by nvasquedr** [Apt3kStudio/Phone#64]
Create Icons for the 3 different features we will offer. Also suggest which icons we should use for more genetic buttons such as (settings, Home, Add, Delete, OK/Confirm)

Duplicate Issue #63 

### Requirements
- [x] Add Sound Icon to the phone Home screen
- [x] Add Vibration Icon to the phone home page
- [x] Add Flash Icon to the phone home page 

### images sources
Link to main features: 

1. [Vibrate Icon](https://drive.google.com/open?id=1GH0MMzeBpZSlOSTdzYEk5FFyCP9dXEQF)

2. [Sound Icon](https://drive.google.com/open?id=16R5J6tCLvSGF99FOa22ZlW2seRlCRaZd)

3. [Flash Icon](https://drive.google.com/open?id=1FUr5tnW3opCYlnV-ryZk2FaI5-2duJJ-)

**Comment by Apt3k** [comment]
Link to 3 main features: https://drive.google.com/drive/u/2/folders/1Rd37vqORTWiRPxsUPYFSoh-nyOAQTH9r

**Comment by Apt3k** [comment]
Icons & Dimension
[Material Design.pdf](https://github.com/Apt3kStudio/Phone/files/3145752/Material.Design.pdf)

**Comment by jagomez16** [comment]
We need to create a tap event that link the feature icons for each functions, @dioscarr how can we do this?
