### ISSUE TITLE
Background Thread - Listener

### ISSUE THREAD

**Issue by dioscarr** [Apt3kStudio/Phone#69]
## Background Thread - Listener
The phone app should be listening for watch activity while it is close. It should also be listening for Firebase base activity while the app is close.

Task:
- [x] Add Watch Background Listening Service. 
> This should be explore more..
- [x] Add Firebase Listening Service
> This should be responsible for Web Port Event Triggers. This should be explore more..

**Comment by jagomez16** [comment]
@dioscarr I believe you are done with this issue. Before closing, I see you would like to explore more "Watch Background Listening Service" and "Firebase Listening Service". In what direction you want to explore more these subject so I can create a future issue.

**Comment by dioscarr** [comment]
Not Removing the listeners would leave the app listening on the background. We should follow up on further implemetation.
